// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pedagio.Data;

namespace Pedagio.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20191004134716_AddPassagens")]
    partial class AddPassagens
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Pedagio.Data.Entities.Pessoa", b =>
                {
                    b.Property<int>("PessoaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bairro");

                    b.Property<int>("Cep");

                    b.Property<int>("Cnpj");

                    b.Property<DateTime>("DataCad");

                    b.Property<string>("Email");

                    b.Property<string>("Endereco");

                    b.Property<string>("Login");

                    b.Property<string>("Nome");

                    b.Property<string>("NomeFantasia");

                    b.Property<string>("Numero");

                    b.Property<int>("PessoaIdAlt");

                    b.Property<int>("PessoaIdCad");

                    b.Property<int>("PessoaIdEmp");

                    b.Property<string>("Senha");

                    b.Property<string>("Telefone1");

                    b.Property<string>("Telefone2");

                    b.Property<int>("TipoPessoaId");

                    b.Property<DateTime>("dataAlt");

                    b.HasKey("PessoaId");

                    b.HasIndex("TipoPessoaId");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("Pedagio.Data.Entities.TipoPessoa", b =>
                {
                    b.Property<int>("TipoPessoaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataAlt");

                    b.Property<DateTime>("DataCad");

                    b.Property<string>("Nome");

                    b.HasKey("TipoPessoaId");

                    b.ToTable("TipoPessoas");
                });

            modelBuilder.Entity("Pedagio.Data.Entities.Pessoa", b =>
                {
                    b.HasOne("Pedagio.Data.Entities.TipoPessoa", "TipoPessoa")
                        .WithMany()
                        .HasForeignKey("TipoPessoaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
